Fix IE by using two hyphens instead of 1 (ie --browser)
Test fails with below error when using -browser instead of --browser.

Tests run: 5, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 1.457 sec <<< FAILURE! - in TestSuite
init(com.streambox.eslstest.pages.LoginPageLiveTest)  Time elapsed: 1.295 sec  <<< FAILURE!
org.openqa.selenium.WebDriverException: Error forwarding the new session
cannot find :
Capabilities [{platform=ANY, ensureCleanSession=true, ignoreProtectedModeSettings=true,
ie.ensureCleanSession=true, browserName=internet explorer, version=}]
Command duration or timeout: 320 milliseconds
Build info: version: '2.40.0', revision: '4c5c0568b004f67810ee41c459549aa4b09c651e', time: '2014-02-19 11:13:01'
System info: host: 'demos-MacBook-Pro-2.local', ip: '192.168.1.10', os.name: 'Mac OS X', os.arch:
'x86_64', os.version: '10.8.5', java.version: '1.6.0_65'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)